### ISSUE TITLE
Check for misconfigured upstream in opscode-push-jobs-server.rb

### ISSUE THREAD

**Issue by nrgetik** [teknofire/gatherlogs-inspec-profiles#3]
This can happen especially when someone changes DNS on their Chef Server and neglects to update `opscode-push-jobs-server.rb` with the new name. From `/var/log/opscode/nginx/current`:

```
2018-05-29_20:56:34.75160 nginx: [emerg] host not found in upstream "CHEF_SERVER_FQDN:10003" in /var/opt/opscode/nginx/etc/addon.d/10-push_jobs_upstreams.conf:5
```

**Comment by teknofire** [comment]
![monosnap 2018-05-31 09-46-47](https://user-images.githubusercontent.com/3766/40795651-95848c30-64b7-11e8-96c2-7ebc989102ef.png)
